name : Postman Collection Workflow

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * *
    - cron : 00 04 * * 1-5


jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.2

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '22'

      - name: Install newman and reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra 

      - name: Run postman collection with new man
        run: |
            newman run 'Pheonix Softwate Copy.postman_collection.json' \
            -e QA.postman_environment.json \
            -d testdata.csv \
            -r cli,htmlextra

      - name: Newman Report
        uses: actions/upload-artifact@4.6.2
        with:
          name: Newman Report
          path: newman/*.html
        
      
    
